language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
before_install:
    - python --version
    - pip install -U pip
    - pip install -U pytest
    - pip install codecov
    - pip install pytest-cov
install:
    - pip install scipy
    - pip install numpy
    - pip install matplotlib
    - git clone https://tjstruck@bitbucket.org/gutenkunstlab/dadi.git
    - cd dadi
    - git checkout devel
    - python setup.py install
    - cd ..
    - python setup.py install
script: pytest -vv --cov=. --cov-report term-missing
after_success:
    - codecov
