language: python
python:
    - "3.8"
    - "3.9"
before_install:
    - python --version
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - source "$HOME/miniconda/etc/profile.d/conda.sh"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
install:
    # Replace dep1 dep2 ... with your dependencies
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip pytest codecov pytest-cov ndcctools scipy numpy matplotlib
    - conda activate test-environment
    # - conda install conda install -y -c conda-forge 
    # - conda install -y scipy
    # - conda install -y numpy
    # - conda install -y matplotlib
    - cd ..
    - git clone https://tjstruck@bitbucket.org/gutenkunstlab/dadi.git
    - cd dadi
    - git checkout devel
    - python setup.py install
    - cd ../dadi-cli
    - python setup.py install
script: pytest -vv --cov=. --cov-report term-missing
after_success:
    - codecov
