language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
install:
    - pip install scipy
    - pip install numpy
    - pip install matplotlib
    - pip install dadi
    - python setup.py install
script: pytest