language: python
python:
    - "3.8"
    - "3.9"
before_install:
    - python --version
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - source "$HOME/miniconda/etc/profile.d/conda.sh"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
install:
    - conda create -y -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip pytest codecov pytest-cov scipy numpy matplotlib
    - conda activate test-environment
    - conda install -y -c conda-forge ndcctools
    - conda install -c anaconda dill
    - cd ..
    - git clone https://tjstruck@bitbucket.org/gutenkunstlab/dadi.git
    - cd dadi
    - git checkout devel
    - python setup.py install
    - cd ../dadi-cli
    - python setup.py install
script: pytest -vv --cov=. --cov-report term-missing
after_success:
    - codecov
