name: dadi-cli
channels:
  - conda-forge
  - bioconda
dependencies:
  - codecov
  - gcc
  - gfortran
  - demes
  - dill==0.3.4
  - matplotlib
  - ndcctools==7.4.3
  - nlopt
  - numpy
  - pip
  - pytest-cov
  - python==3.8
  - scipy
  - setuptools==58.0.4
  - snakemake==7.1.1
  - pip:
      - git+https://bitbucket.org/gutenkunstlab/dadi@devel
      - .
