name: dadi-cli
channels:
        - conda-forge
        - bioconda
dependencies:
        - dill==0.3.4
        - codecov
        - matplotlib
        - ndcctools==7.4.3
        - numpy
        - pip
        - pytest-cov
        - python==3.8
        - scipy
        - snakemake==7.1.1
        - pip:
            - .
